name: Lint PR Title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-pr-title:
    name: Lint PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Install commitlint
        run: |
          npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Lint PR title
        run: |
          echo "${{ github.event.pull_request.title }}" | commitlint
